install: ./install-dependencies.sh
install:
  - bundle install --path vendor/bundle
  - npm install
  install: true
  script: bundle exec thor build
  script:
- bundle exec rake build
- bundle exec rake builddoc
script: bundle exec rake build && bundle exec rake builddoc
deploy:
  skip_cleanup: true