language: node_js
node_js:
  - "stable"

  cache: npm

  before_install:
  - npm i -g npm@version-number

  install:
    - npm install

    cache:
    directories:
    - "node_modules"

    efore_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version version-number
  - export PATH="$HOME/.yarn/bin:$PATH"

  cache:
  yarn: true